apiVersion: v1
kind: ResourceQuota

metadata:
  name: platform-prod-quota
  namespace: platform-prod

spec:
  hard:
    requests.cpu: "15"
    requests.memory: 30Gi
    limits.cpu: "25"
    limits.memory: 60Gi
